version: '3.9'
services:
  route-wings-app-db:
    image: postgres:16.2
    container_name: route-wings-app-db
    environment:
      POSTGRES_DB: routewings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      route-wings:
        aliases:
          - db.routewings.com
    ports:
      - "5432:5432"
    volumes:
      - route-wings_data:/var/lib/postgresql/data

  route-wings-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: route-wings-app:latest
    container_name: route-wings-app
    networks:
      route-wings:
        aliases:
          - app.routewings.com
    ports:
      - "8000:8000"

  route-wings-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: route-wings-ui:latest
    container_name: route-wings-ui
    networks:
      route-wings:
        aliases:
          - ui.routewings.com
    ports:
      - "3000:3000"

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    networks:
      route-wings:
        aliases:
          - sonar.routewings.com
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

networks:
  route-wings: { }

volumes:
  route-wings_data:
  sonarqube_data:
  sonarqube_extensions:
